In [4]:
import numpy as np
import pandas as pd
from collections import defaultdict 
import random
import math

pd.set_option('max_columns', None)

import collections
compare = lambda x, y: collections.Counter(x) == collections.Counter(y)

In [5]:
df_food = pd.read_csv('data/food_data.csv')
cols = [4, 8, 9]
df_food.drop(columns = df_food.columns[cols], axis=1, inplace=True)
#df_food.sort_values(by=df_food.columns[2])
df_food[df_food.columns[2:]] = df_food[df_food.columns[2:]] * 100

cols=['Calcium (g)', 'Phosphorus (g)','Potassium (g)','Sodium (g)']
df_food[cols] = df_food[cols] / 100

cols=['Phosphorus (g)','Potassium (g)','Sodium (g)']
df_food[cols] = df_food[cols] / 10

df_food = df_food.iloc[:,[0,1,2,9,10,11]]

df_food

name emoji  Calories (kcal)  Vitamin B6 (mg)  Vitamin A (IU)  \
0          grapes     🍇             69.0            0.086            66.0   
1           melon     🍈             28.0            0.163             0.0   
2      watermelon     🍉             30.0            0.045           569.0   
3       tangerine     🍊             53.0            0.078           681.0   
4           lemon     🍋             29.0            0.080            22.0   
5          banana     🍌             89.0            0.367            64.0   
6       pineapple     🍍             50.0            0.112            58.0   
7       red apple     🍎             63.0            0.045            38.0   
8     green apple     🍏             58.0            0.037           100.0   
9            pear     🍐             57.0            0.029            25.0   
10          peach     🍑             39.0            0.025           326.0   
11       cherries     🍒             63.0            0.049            64.0   
12     strawberry     🍓             32.0            0.047            12.0   
13      kiwifruit     🥝             61.0            0.063            87.0   
14         tomato     🍅             18.0            0.080           833.0   
15        avocado     🥑            160.0            0.257           146.0   
16       eggplant     🍆             25.0            0.084            23.0   
17         potato     🥔             90.0            0.286         19218.0   
18         carrot     🥕             41.0            0.138         16706.0   
19           corn     🌽             96.0            0.139           263.0   
20     hot pepper     🌶             40.0            0.506           952.0   
21       cucumber     🥒             15.0            0.040           105.0   
22       mushroom     🍄             22.0            0.104             0.0   
23        peanuts     🥜            567.0            0.348             0.0   
24       chestnut     🌰            196.0            0.352            26.0   
25          bread     🍞            274.0            0.111             2.0   
26      croissant     🥐            406.0            0.058           744.0   
27   french bread     🥖            272.0            0.107             1.0   
28       pancakes     🥞            227.0            0.046           196.0   
29         cheese     🧀            393.0            0.071          1047.0   
30           beef     🍖            217.0            0.758             5.0   
31        chicken     🍗            184.0            0.413            68.0   
32          bacon     🥓            898.0            0.005            37.0   
33      hamburger     🍔            254.0            0.110            75.0   
34   french fries     🍟            312.0            0.372             0.0   
35          pizza     🍕            266.0            0.080           358.0   
36         hotdog     🌭            247.0            0.050             0.0   
37           taco     🌮            226.0            0.090           131.0   
38        burrito     🌯            180.0            0.097           277.0   
39        popcorn     🍿            500.0            0.209            11.0   
40  rice crackers     🍘            416.0            0.554             0.0   
41           rice     🍚            130.0            0.050             0.0   
42      spaghetti     🍝            157.0            0.049             0.0   
43   fried shrimp     🍤            308.0            0.060           109.0   
44      ice cream     🍨            222.0            0.048           589.0   
45       doughnut     🍩            417.0            0.027            39.0   
46         cookie     🍪            497.0            0.017             4.0   
47           cake     🍰            371.0            0.041           140.0   
48  chocolate bar     🍫            518.0            0.020            81.0   
49          candy     🍬            394.0            0.003             0.0   
50   custard flan     🍮            145.0            0.044           161.0   
51       

In [6]:
min_rdi = pd.read_csv('data/min_rdi.csv')
min_rdi = min_rdi.iloc[:,[0,7,8,9]]
min_rdi.head()

Calories (kcal)  Vitamin B6 (mg)  Vitamin A (IU)  Vitamin B12 (ug)
0             2000              1.3            3000               2.4

In [308]:
prod_list = ['cheese', 'milk', 'pizza', 'cookie']
products = df_food[df_food['name'].isin(prod_list)]
np_products = products.to_numpy()

products.head(25)

name emoji  Calories (kcal)  Vitamin B6 (mg)  Vitamin A (IU)  \
29  cheese     🧀            393.0            0.071          1047.0   
35   pizza     🍕            266.0            0.080           358.0   
46  cookie     🍪            497.0            0.017             4.0   
52    milk     🥛             64.0            0.042           138.0   

    Vitamin B12 (ug)  
29              3.06  
35              0.42  
46              0.00  
52              0.36

In [304]:
class Branch:
    def __init__(self):
        self.nutritions = np.zeros(4)
        self.calories = 0
        self.history = []
        self.used = False
        self.fitness = 0
        self.entropy = 0

In [305]:
branches = []
branches.append(Branch())
print(branches[0].history)
print(branches[0].nutritions)
    
    

[]
[0. 0. 0. 0.]


In [309]:
#A = 
#GEPP(np.copy(A), np.copy(b), doPricing = False)
np_min_rdi = min_rdi.to_numpy()
A = np_products[:,2:].copy()
A = np.rot90(A, k=-1, axes=(0, 1))

np_min_rdi = min_rdi.to_numpy()
b = np.rot90(np_min_rdi, k=-1, axes=(0, 1))
g = GEPP(np.copy(A), np.copy(b), doPricing = False)



In [310]:
g._elimination() 
g._backsub() 

In [315]:
(A[0] * g.x).sum()

1999.9999999999998

In [317]:
g.x

array([18.98918199, -1.06100211,  8.87369593, -2.66766595])

In [167]:
def normalize(b):
    b.nutritions = b.nutritions.copy() / min_rdi.loc(0)[0]
    return b

In [168]:
branches = list(map(normalize, branches))

In [195]:
entropy_coef = 0.8
for b in branches:
    val_sum = sum(collections.Counter(b.history).values())
    b.entropy = - sum([i / val_sum * math.log(i / val_sum, 2) 
                     for i in list(collections.Counter(b.history).values())])
    
    #fitness = 1 / SUM(SE) * entropy
    fit = 1 / sum([s ** 2 for s in b.nutritions - 1])
    b.fitness = fit - fit * (1 - b.entropy) * entropy_coef

In [196]:
branches.sort(key = lambda b: b.fitness, reverse = True)

In [197]:
print('BEST DIETS')
for i in range(10):
    print(branches[i].history)
    print(branches[i].fitness)
    print(branches[i].entropy)

BEST DIETS
['cheese', 'cheese', 'cheese', 'cheese', 'cheese']
0.006672366333264384
-0.0
['cheese', 'cheese', 'cheese', 'cheese', 'cheese', 'cheese']
0.004356978143729474
-0.0


IndexError: list index out of range

In [188]:
i = 0
1 / sum((branches[i].nutritions - 1) ** 2)

0.03336183166632193

In [181]:
branches[i].fitness

0.03336183166632193

In [260]:
val_sum = sum(collections.Counter(branches[-1].history).values())
- sum([i / val_sum * math.log(i / val_sum, 2)
       for i in list(collections.Counter(branches[-1].history).values())])

-0.0

In [369]:
collections.Counter(branches[-1].history)

Counter({'cheese': 5, 'milk': 2})

In [211]:
a = np.array([[2,1,-1,8],[-3,-1,2,-11],[-2,1,2,-3]])
b = [[2,1,-1,8],[-3,-1,2,-11],[-2,1,2,-3]]
gauss(b)

[2.0, 3.0000000000000004, -0.9999999999999999]

In [291]:
import numpy as np


class GEPP():
    """
    Gaussian elimination with partial pivoting.
    input: A is an n x n numpy matrix
           b is an n x 1 numpy array
    output: x is the solution of Ax=b
            with the entries permuted in
            accordance with the pivoting
            done by the algorithm
    post-condition: A and b have been modified.
    :return
    """

    def __init__(self, A, b, doPricing=True):
        #super(GEPP, self).__init__()

        self.A = A                      # input: A is an n x n numpy matrix
        self.b = b                      # b is an n x 1 numpy array
        self.doPricing = doPricing

        self.n = None                   # n is the length of A
        self.x = None                   # x is the solution of Ax=b

        self._validate_input()          # method that validates input
        #self._elimination()             # method that conducts elimination
        #self._backsub()                 # method that conducts back-substitution

    def _validate_input(self):
        self.n = len(self.A)
        if self.b.size != self.n:
            raise ValueError("Invalid argument: incompatible sizes between" +
                             "A & b.", self.b.size, self.n)

    def _elimination(self):
        """
        k represents the current pivot row. Since GE traverses the matrix in the
        upper right triangle, we also use k for indicating the k-th diagonal
        column index.
        :return
        """

        # Elimination
        for k in range(self.n - 1):
            if self.doPricing:
                # Pivot
                maxindex = abs(self.A[k:, k]).argmax() + k
                if self.A[maxindex, k] == 0:
                    raise ValueError("Matrix is singular.")
                # Swap
                if maxindex != k:
                    self.A[[k, maxindex]] = self.A[[maxindex, k]]
                    self.b[[k, maxindex]] = self.b[[maxindex, k]]
            else:
                if self.A[k, k] == 0:
                    raise ValueError("Pivot element is zero. Try setting doPricing to True.")
            # Eliminate
            for row in range(k + 1, self.n):
                multiplier = self.A[row, k] / self.A[k, k]
                self.A[row, k:] = self.A[row, k:] - multiplier * self.A[k, k:]
                self.b[row] = self.b[row] - multiplier * self.b[k]

    def _backsub(self):
        # Back Substitution

        self.x = np.zeros(self.n)
        for k in range(self.n - 1, -1, -1):
            self.x[k] = (self.b[k] - np.dot(self.A[k, k + 0:], self.x[k + 0:])) / self.A[k, k]


def main():
    A = np.array([[1., -1., 1., -1.],
                  [1., 0., 0., 0.],
                  [1., 1., 1., 1.],
                  [1., 2., 4., 8.]])
    b = np.array([[14.],
                  [4.],
                  [2.],
                  [2.]])

    GaussElimPiv = GEPP(np.copy(A), np.copy(b), doPricing = False)
    
    GaussElimPiv = GEPP(A, b)
    print(GaussElimPiv.x)
    print(GaussElimPiv.A)
    print(GaussElimPiv.b)
    
main()

None
[[ 1. -1.  1. -1.]
 [ 1.  0.  0.  0.]
 [ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]]
[[14.]
 [ 4.]
 [ 2.]
 [ 2.]]
